services:
    twitter_like_factory:
        class: Follower\TwitterBundle\Service\Factory\Like
        arguments: ["@service_container"]
        calls:
            - [login]

    twitter_follow_factory:
        class: Follower\TwitterBundle\Service\Factory\Follow
        arguments: ["@service_container"]
        calls:
            - [login]

    twitter_unfollow_factory:
        class: Follower\TwitterBundle\Service\Factory\Unfollow
        arguments: ["@service_container"]
        calls:
            - [login]

    twitter_search_factory:
        class: Follower\TwitterBundle\Service\Factory\Search
        arguments: ["@service_container"]
        calls:
            - [login]


    twitter_profile_factory:
        class: Follower\TwitterBundle\Service\Factory\Profile
        arguments: ["@service_container"]
        calls:
            - [login]


    twitter_reshare_factory:
        class: Follower\TwitterBundle\Service\Factory\ReShare
        arguments: ["@service_container"]
        calls:
            - [login]


    twitter_messagesend_factory:
        class: Follower\TwitterBundle\Service\Factory\Message
        arguments: ["@service_container"]
        calls:
            - [login]

    twitter_follower:
        class: Follower\TwitterBundle\Service\Follower
        arguments: ["@service_container"]

    twitter_unfollower:
        class: Follower\TwitterBundle\Service\Unfollower
        arguments: ["@service_container"]

    twitter_liker:
        class: Follower\TwitterBundle\Service\Liker
        arguments: ["@service_container"]

    twitter_resharer:
        class: Follower\TwitterBundle\Service\ReSharer
        arguments: ["@service_container"]

    twitter_status_checker:
        class: Follower\TwitterBundle\Service\StatusChecker
        arguments: ["@service_container"]

    twitter_message_sender:
        class: Follower\TwitterBundle\Service\MessageSender
        arguments: ["@service_container"]
